name: Upload Website to s3 bucket

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set AWS credentials
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        run: aws s3 sync ./build/. s3://githu-to-s3
